Added Tests For Endpoint Service
eclipse-kapua/kapua pull request #2808
Opened 2020-01-08 12:29 UTC by zanpizmoht

Added tests for creating, deleting and editing Endpoints.

Signed-off-by: zanpizmoht <zan.pizmoht@comtrade.com>

In this PR new test scenarios for Endpoint service are created.

**Related Issue**
_None_

**Description of the solution adopted**
Test scenarios that are added in this PR are checking functionalities regarding Endpoints. All scenarios are added to `EndpointServiceI9n.feature`. Scenarios are testing if Endpoints are correctly created, edited or deleted. There are also two scenarios added for testing Endpoint in different accounts.

**Screenshots**
/

2020-01-10 15:20 UTC, Coduz commented
CQ submitted: [CQ 21396](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21396)

2020-01-10 15:47 UTC, Coduz approved these changes

2020-01-20 10:07 UTC, LeoNerdoG reviewed
Hi @zanpizmoht,
I have reviewed the PR and there are some changes that need to be made. 
Please take a look at the comments and fix the selected lines.

2020-01-20 10:07 UTC, LeoNerdoG reviewed
Hi @zanpizmoht,
I have reviewed the PR and there are some changes that need to be made. 
Please take a look at the comments and fix the selected lines.

2020-01-31 08:01 UTC, LeoNerdoG requested changes
Hey @zanpizmoht,
I have checked this PR again and there are still some comments that need to be addessed. Please review them and fix them accordingly.

2020-01-31 08:01 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/endpoint/EndpointServiceI9n.feature
> +  Create a endpoint with Schema containing "http://"
This should be changed to "https://"!

2020-02-06 14:20 UTC, LeoNerdoG approved these changes
Everything is OK now from QA side. 
@Coduz can you please check the status of CQ and rerun failing tests so we will have accurate codeCov? 

thanks!

2020-03-10 08:59 UTC, Coduz commented
[CQ approved](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21396#c5) 🎉

2020-03-11 08:10 UTC, merged