Added tests for Group service
eclipse-kapua/kapua pull request #2809
Opened 2020-01-08 13:54 UTC by zanpizmoht

Added tests for adding, deleting and editing groups, and adding devices to groups.

Signed-off-by: zanpizmoht <zan.pizmoht@comtrade.com>

Brief description of the PR.
Test scenarios for Groups are added in this PR.

**Related Issue**
_None_

**Description of the solution adopted**
Test scenarios that are added in this PR are checking functionalities regarding Groups. All scenarios are added to `GroupService.feature`. Scenarios are testing if Groups are correctly created, edited or deleted and if Devices can be added to Groups.

**Screenshots**
/

2020-01-10 14:42 UTC, Coduz approved these changes

2020-01-10 15:00 UTC, Coduz commented
CQ submitted: [CQ 21395](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21395)

2020-01-21 06:40 UTC, LeoNerdoG requested changes
Hi @zanpizmoht,
I have reviewed the PR and there are some changes that need to be made.

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    And I add device to group
Change step name to: "And I add device "Device1" to group "Group1"

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    Then Device is in groups Assigned Devices
Change step name to: "Then Device "Device1" is in Assigned Devices of group "Group1" so we can use this more clearly in other scenarios as well.

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +  Scenario: Change Group With Description of Device
Change title to: "Moving Device From One Group With Description to Another

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +  Go to devices, create a device ("Device1") and add created group to it.
Change description to: "Go to devices, create a device ("Device1") and add it to the created group."

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +  Create another group and add it to "Device1"
Change description to: "Create another group and add device ("Device1") to it."

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +  Kapua should throw Exception.
Change description to: "Kapua should throw Exception  when checking for device in "Group1"".

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    And I add device to group
Change step name to: "And I add device "Device1" to group "Group1""

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    Then Device is in groups Assigned Devices
Change step name to: "Then Device "Device1" is in Assigned Devices of group "Group1"

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    And I change devices group
Change step name to: "And I move device "Device1" from group "Group1" to group "Group2"

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    Then Device is in groups Assigned Devices
Change step name to: "Then Device "Device1" is in Assigned Devices of group "Group2"

2020-01-21 06:40 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +    Then Device is not in groups Assigned Devices
Change step name to: "Then Device "Device1" is not in Assigned Devices of group "Group1""

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    @And("^I add device to group$")
Change step name to: "I add device "Device1" to group "Group1""

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    public void iAddDeviceToGroup() throws Exception{
Change method name to: "public void iAddDeviceToGroup(String deviceName, String groupName) throws Exception{

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +        Device device = (Device) stepData.get("Device");
Change method implementation, so it accepts the parameters that are given to it; do not use "stepData.get("Device")

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +        Group group = (Group) stepData.get("Group");
Change method implementation, so it accepts the parameters that are given to it; do not use "stepData.get("Group")

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    @When("^I change devices group to No Group$")
Change step name to: "Then Device "Device1" is removed from all groups".

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    public void iChangeDevicesGroupToNoGroup() throws Exception{
Add parameter to the method: "public void iChangeDevicesGroupToNoGroup(String deviceName) throws Exception{"

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +        Device device = (Device) stepData.get("Device");
Use "Device1" paramater and not "last" device.

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    @And("^I create (\\d+) devices and add them to group$")
Change step name to: "@And("^I create (\\d+) devices and add them to group "Group1"$")

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    public void iCreateDevicesAndAddThemToGroup(int numberOfDevices) throws Exception {
Change method implementation so it accepts group parameter: " public void iCreateDevicesAndAddThemToGroup(int numberOfDevices, String group) throws Exception {"

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    @And("^Device has no group$")
This is not used anywhere?

2020-01-21 06:40 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    @And("^I update device$")
This is also not used here?

2020-01-21 06:41 UTC, LeoNerdoG requested changes
Hi @zanpizmoht,
I have reviewed the PR and there are some changes that need to be made.

2020-01-30 13:24 UTC, LeoNerdoG reviewed
Hey, @zanpizmoht, there are only 2 minor things left to change. 
Please change them and push to PR. 
@Coduz this PR can be labeled as "QA Approved" label.

2020-01-30 13:24 UTC, LeoNerdoG commented on qa/integration/src/test/resources/features/authorization/GroupService.feature
> +  Scenario: Creating Unique Tag With Long Description
Please change this title to: "Creating Unique Group With Long Description" becasue we are creating groups here and not tags =)

2020-02-07 12:52 UTC, LeoNerdoG approved these changes
Hi @zanpizmoht,
I have checked all the changes and everything is OK now. 
@coduz, can you please restart the failing tests and merge when CQ passes?

2020-03-03 11:55 UTC, LeoNerdoG approved these changes

2020-03-10 09:00 UTC, Coduz commented
[CQ Approved!](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21395#c6) 🎉

2020-03-10 16:20 UTC, Coduz requested changes

2020-03-10 16:20 UTC, Coduz commented on qa/integration/src/test/resources/features/user/UserPermissionI9n.feature
> +>>>>>>> Added tests for Group service
Please remove the merge meta data

2020-03-11 07:53 UTC, zanpizmoht commented
Hi @Coduz,
I fixed the errors and I saw Travis just passed so this PR is ready to be merged.
Regards, Zan

2020-03-11 08:12 UTC, Coduz approved these changes

2020-03-11 08:12 UTC, merged