Role unit test
eclipse-kapua/kapua pull request #2843
Opened 2020-01-31 14:02 UTC by code-incubus

Signed-off-by: code-incubus nemanja.milutinovic@comtrade.com

Added unit test scenarios for Role Service.

**Related Issue**
_None_

**Description of the solution adopted**
Test scenarios that are added in this PR are checking functionalities regarding Roles. All scenarios are added to _RoleServiceUnitTests.feature_. Scenarios are testing if Roles are correctly created, edited or deleted. 

**Screenshots**
/

**Any side note on the changes made**
/

2020-02-03 08:17 UTC, LeoNerdoG requested changes
Hej @code-incubus,
I have reviewed this PR and there are some changes to be made. 
Plase fix this as soon as you can. 
@Coduz after the changes are made and all the tests pass and codeCove is OK, please merge this.

2020-02-03 08:17 UTC, LeoNerdoG commented on service/security/test/src/test/resources/features/RoleServiceUnitTests.feature
> +     After that tr to update role name to "null".
Change description to: " After that try to update role name to "null"."

2020-02-03 08:17 UTC, LeoNerdoG commented on service/security/test/src/test/resources/features/RoleServiceUnitTests.feature
> +     then try to update role name with special characters e.g "roleName$%^".
Change description line to: then try to update role name with special characters( e.g "roleName%")."

2020-02-03 08:17 UTC, LeoNerdoG commented on service/security/test-steps/src/main/java/org/eclipse/kapua/service/authorization/steps/AuthorizationServiceSteps.java
> +    @Then("^I update the role name with special characters$")
Please change step name to: " update the role name with special characters ""#$%&'(‹›€ı–......."

2020-02-03 08:17 UTC, LeoNerdoG commented on service/security/test-steps/src/main/java/org/eclipse/kapua/service/authorization/steps/AuthorizationServiceSteps.java
> +    public void iUpdateTheRoleNameWithSpecialCharacters() throws Exception {
**Please change implementation to:** 

```
public void iUpdateTheRoleNameWithSpecialCharacters(String invalidSymbols) throws Exception {
        RoleCreator roleCreator = roleFactory.newCreator(SYS_SCOPE_ID);
            for (int i = 0; i < invalidSymbols.length(); i++) {
                String roleName = "roleName" + invalidSymbols.charAt(i);
                 roleCreator.setName("roleName" + i);

            try {
                primeException();
                stepData.remove("Role");
                Role role = roleService.create(roleCreator);
                role.setName("roleName" + invalidSymbols.charAt(i));
                roleService.update(role);
                stepData.put("Role", role);
            } catch (KapuaException ex) {
                verifyException(ex);
            }
        }
    }
```

2020-02-03 08:17 UTC, LeoNerdoG commented on service/security/test/src/test/resources/features/RoleServiceUnitTests.feature
> +     Then I update the role name with special characters
**Please change step name to:** 
Then I update the role name with special characters "!"#$%&'()=⁄@‹›€ı–......."

Please also change implementation!!!! (See comment above)

2020-02-03 09:03 UTC, code-incubus commented
Done. @LeoNerdoG

2020-02-03 11:40 UTC, Coduz requested changes
Small thing.

Could you please remove `()` when declaring the `@Inject` annotation? 
Also, since the init of the `RoleServiceImpl` has changes, can you please check that the runtime is not affected by that? If you didn't do it already. Running a console and CRUDing a Role should be enough.

Thanks,

- Alberto

2020-02-03 13:17 UTC, code-incubus commented
Hi @Coduz, @LeoNerdoG 
Checked. Everything works fine and all the changes are made.

2020-02-04 06:09 UTC, LeoNerdoG commented
Hey @Coduz,
I have checked this PR and from QA stanpoint everything is OK. 
All the tests have passed, code coverage has increased, no CQ is needed, so I guess we can merge this. 

Leo

2020-02-10 09:21 UTC, Coduz approved these changes

2020-02-10 14:52 UTC, LeoNerdoG approved these changes

2020-02-11 11:09 UTC, merged