Added unit tests for translator part1
eclipse-kapua/kapua pull request #2941
Opened 2020-04-21 14:13 UTC by code-incubus

Signed-off-by: code-incubus <nemanja.milutinovic@comtrade.com>

Added tests for:
- KapuaTranslatorApi
- TranslatorDataMqttKura
- TranslatorResponseMqttKura
- TranslatorDataKuraMqtt 

**Related Issue**
/

**Description of the solution adopted**
This is the first part of tests regarding Translators.

**Screenshots**
/
**Any side note on the changes made**
/

2020-04-22 09:30 UTC, Coduz commented
Converted to draft since it still need some work on that

2020-04-23 09:11 UTC, LeoNerdoG requested changes
Hey @code-incubus,
I have finally reviewed this branch and there are some changes to be made. 
Plase address them and then push the changes.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Finding existing translator to null translator
Please change the scenario name to: "Translating CommandRequestMessage to null"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Finding translator "TranslatorAppCommandKapuaKura"
Please change scenario name to: "Translating "CommandRequestMessage" to "KuraRequestMessage""

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Finding null translator to existing one
Please change scenario name to: "Translating null to KuraRequestMessage"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Finding null translator
Please change scenario name to: "Translating empty message to empty message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Finding wrong translator
Please change scenario name to: "Translating from "AssetRequestMessage" to "AssetResponseMessage""

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with invalid payload and valid topic into kura data message
Please  change scenario name to: "Translation of mqtt message with invalid payload and valid topic into kura data message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Given I create mqtt message with valid payload "invalidPayload" and valid topic "kapua-sys/rpione3/DEPLOY-V2/GET/packages"
Please change step name to: "Given I create mqtt message with invalid payload "invalidPayload" and valid topic "kapua-sys/rpione3/DEPLOY-V2/GET/packages""

there is a syntax error in the step name, it has to be ...with invalid payload... not "valid".

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with valid payload and valid topic into kura data message
Please change scenario name to: "Translation of mqtt message with valid payload and valid topic into kura data message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Then I got kura data message with proper payload metrics
Can you please make this more specific, checking if proper payload is in the message? 
I mean..it is ok to check if it's not null, but it is also vital to check if the data is as it is supposed to be.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with empty payload into kura data message
Please change scenario name to: "Translation of mqtt message with empty payload into kura data message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with invalid payload and invalid topic into kura response
Please change scenario name to: "Translation of mqtt message with invalid payload and invalid topic into kura response message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Creating mqtt message with invalid payload and invalid topic. Trying to translate it into kura response.
Please change description to: " Creating mqtt message with invalid payload and invalid topic. Trying to translate it into kura response message."

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with invalid payload and valid topic into kura response
Please change scenario name to: "Translation of mqtt message with invalid payload and valid topic into kura response message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Creating mqtt message with invalid payload and valid topic. Trying to translate it into kura response.
Please change description to: "Creating mqtt message with invalid payload and valid topic. Trying to translate it into kura response message."

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with valid payload and invalid topic into kura response
Please change scenario name to: "Translation of mqtt message with valid payload and invalid topic into kura response message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Creating mqtt message with valid payload and invalid topic. Trying to translate it into kura response.
Please change description to: "Creating mqtt message with valid payload and invalid topic. Trying to translate it into kura response message."

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating of mqtt message with valid payload and valid topic into kura response
Please change scenario name to: "Translation of mqtt message with valid payload and valid topic into kura response message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Check if kura response with proper payload, metrics and correct channel is received.
Please change description to: "Creating mqtt message with valid payload and valid topic. Trying to translate it into kura response message.  Check if kura response message with proper payload, metrics and correct channel is received."

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating kura data message with valid channel and without body and metrics into mqtt message
Pleae change scenario to: "Translation of kura data message with valid channel and without body and metrics into mqtt message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Check if mqtt message with valid topic and empty body is received.
Please change description to: "Checking if mqtt message with valid topic and empty body is received."

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating kura data message with valid channel, metrics and without body into mqtt message
Please change scenario name to: "Translation of kura data message with valid channel, metrics and without body into mqtt message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Creating kura data message with valid channel, metrics and without body. Trying to translate it into mqtt message.
Change description to: "Creating kura data message with valid channel, metrics but without body. Trying to translate it into mqtt message."

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Given I create kura data message with channel with scope "kapua-sys", client id "rpione3" and payload without body and with metrics
Please change the step name to: "Given I create kura data message with channel with scope "kapua-sys", client id "rpione3", valid payload and metrics but without body"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Then I got mqtt message with channel with scope "kapua-sys", client id "rpione3" and non empty body
Then I get

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +  Scenario: Translating kura data message with valid channel, body and metrics into mqtt message
Please change the scenario name to: "Translation of kura data message with valid channel, body and metrics into mqtt message"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iTryToProvideInvalidTopic(String payload, String topic) {
Please change method name to: "public void creatingMqttMessage(String payload, String topic)" becasue you have 6 options here and not only one.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iGotKuraResponseMessageWithPayloadAndChannelWithAndData() {
Plesase change the method name to: "public voidkuraResponseMessageWithPayloadAndChannelAndData()"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iGotMqttMessageWithChannelWithClientIdScopeAndWithoutMetricsAndBodyInPayload(String scope, String clientId) {
Please change method name to: "mqttMessageWithChanneScopeClienIDandBody()" and even this is too long... you can add a comment bellow, but the method name should never be this long.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iGotKuraResponseMessageChannelWithAndData(String replyPart, String requestId, String appId, String messageClassification, String scope, String clientId) {
Change method name to: "kuraResponseMessageWithChannelAndData"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iGotKuraResponseMessageWithPayloadBody(String payloadType) {
Change method name to: "kuraResponseMessageWithPayloadBody"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iCreateKuraDataMessageWithChannelWithScopeClientIdAndPayloadWithoutBodyAndWithMetrics(String scope, String clientId) {
Change method name to: "kuraDataMessageWithoutBodyAndMetrics"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iCreateKuraDataMessageWithChannelWithScopeClientIdAndPayloadWithBodyAndMetrics(String scope, String clientId) {
Change method name to: "fullKuraDataMessage"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iGotKuraDataMessageChannelWithScopeClientIdAndProperSemanticPart(String scope, String clientId, List<String> semanticParts) {
Change method name to: "iCreateJmsMessageWithInvalidPayloadAndTopic"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +    public void iGotJmsMessageWithTopicAndEmptyPayloa(JmsTopic topic) {
Change method name to: "iGotJmsMessageWithTopicAndEmptyPayload"

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        assertTrue(kuraResponseMessage.getPayload().getMetrics() != null);
Please change this to assertEquals(), becasue compartin to "!=null" is not enough.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        KuraDataMessage kuraDataMessage = new KuraDataMessage(kuraDataChannel, date, kuraDataPayload);
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        MqttMessage mqttMessage = translatorDataKuraMqtt.translate(kuraDataMessage);
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +            assertTrue(mqttMessage.getPayload().getBody().length != 0);
can you check more specific and not only that is !=0?

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        KuraDataMessage kuraDataMessage = new KuraDataMessage(kuraDataChannel, date, kuraDataPayload);
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        KuraDataMessage kuraDataMessage = new KuraDataMessage(kuraDataChannel, date, kuraDataPayload);
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        KuraDataMessage kuraDataMessage = translatorDataMqttKura.translate(mqttMessage);
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-23 09:11 UTC, LeoNerdoG commented on translator/test-steps/src/main/java/org/eclipse/kapua/translator/test/steps/TranslatorSteps.java
> +        JmsMessage jmsMessage = translatorDataKuraJms.translate(kuraDataMessage);
insert try/catch block, the "stepdata.put" part can be left ouside the try/catch.

2020-04-28 08:52 UTC, LeoNerdoG approved these changes
@code-incubus I have checked the changes and they look OK. 
@coduz - can you please merge this PR since Travis and all tests have successfully passed?

2020-04-28 14:11 UTC, Coduz approved these changes

2020-04-28 14:14 UTC, merged