Added JUnit Tests for KapuaExceptionUtils
eclipse-kapua/kapua pull request #2973
Opened 2020-05-14 06:33 UTC by sonja-ct

Signed-off-by: Sonja <sonja.matic@comtrade.com>

Added Junit Tests for KapuaExceptionUtils

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

2020-05-14 07:23 UTC, LeoNerdoG commented
Hey @Coduz,
I have checked this PR and it looks OK. All tests have passed, CodeCov has reported positive coverage - can you please merge this into develop branch? 
Thanks!

2020-05-14 07:23 UTC, LeoNerdoG approved these changes

2020-05-14 12:09 UTC, Coduz requested changes
Just a small thing to change.
Everything else looks ok.

2020-05-14 12:09 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/util/KapuaExceptionUtilsTest.java
> + * Copyright (c) 2020 Eurotech and/or its affiliates and others
Please update the copyright message to reflect the timespan from the date of the file was created.
So this will be like:
`Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others`

2020-05-14 13:16 UTC, LeoNerdoG approved these changes

2020-05-15 08:27 UTC, sonja-ct commented on commons/src/test/java/org/eclipse/kapua/commons/util/KapuaExceptionUtilsTest.java
> + * Copyright (c) 2020 Eurotech and/or its affiliates and others
Hi @Coduz I have made this change, so can you please merge this into develop branch?  Thanks

2020-05-18 06:10 UTC, LeoNerdoG commented
Hey @Coduz,
this has been fixed, can you please merge it into develop?

2020-05-18 09:52 UTC, Coduz requested changes
Hi @sonja-ct ,

I've just looked at #2977 and #2976 from Žan and re-checked yours if the `assert` usage was not correct. 
Please correct in all places where it has not been used properly.

Thanks,

_Alberto_

2020-05-18 09:52 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/util/KapuaExceptionUtilsTest.java
> +                assertEquals(listOfExpectedExceptions[i].toString(), KapuaExceptionUtils.convertPersistenceException(listOfExceptions[i]).toString());
assertEquals has an overload method that accepts a message as a first argument. So fail invoked in the catch exception is not the correct usage of Assert stuff.
Please change this and also other similar usages.

2020-05-18 14:40 UTC, Coduz approved these changes

2020-05-19 08:57 UTC, Coduz approved these changes

2020-05-19 09:03 UTC, merged