Added JUnit tests for Metatype package - part1
eclipse-kapua/kapua pull request #2979
Opened 2020-05-15 12:24 UTC by code-incubus

Signed-off-by: code-incubus nemanja.milutinovic@comtrade.com

Added JUnit tests for classes in a metatype package:

- EmptyTocdTest.java
- TadImplTest.java
- TattributeImplTest.java
- TdesignateImplTest.java
- TiconImplTest.java
- ToptionImplTest.java

Related Issue
None

Description of the solution adopted
/
Screenshots
/

Any side note on the changes made
/

2020-05-18 06:06 UTC, LeoNerdoG approved these changes

2020-05-18 06:06 UTC, LeoNerdoG commented
Hey @Coduz,
I have reviewd this branch and it looks OK. Can you plese merge it into develop branch? All the tests have successfully passed.

2020-05-18 10:24 UTC, Coduz requested changes

2020-05-18 10:24 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/EmptyTocdTest.java
> +        assertEquals("49", emptyTocd.getId());
While using `assertEquals`, `assertNotEquals` (and so on) they al support a message linked to the `assert*` as a first argument. It is a good practice to add a message that shows which specific assert has failed.

So in this case:
`assertEquals("tocd.id", "49", emptyTocd.getId());`
would make any failure linked to a meaningful message which can avoid to have to look at the code to check what has failed.

2020-05-19 07:22 UTC, code-incubus commented
Hi @Coduz,
I made all the changes that you mentioned above. If something is not ok please let me know.
I'll fix it up quickly.

2020-05-19 09:03 UTC, LeoNerdoG commented
Hey @Coduz,
now this PR looks ok, I think this can be merged.

2020-05-19 11:59 UTC, Coduz approved these changes

2020-05-19 14:55 UTC, merged