Added JUnit tests for Metatype package - part2
eclipse-kapua/kapua pull request #2980
Opened 2020-05-15 12:48 UTC by code-incubus

Signed-off-by: code-incubus nemanja.milutinovic@comtrade.com

Added JUnit tests for classes in a metatype package:

- TmetadataImplTest.java
- TobjectImplTest.java
- TocdImplTest.java
Related Issue
None

Description of the solution adopted
/
Screenshots
/

Any side note on the changes made
/

2020-05-18 10:25 UTC, Coduz requested changes

2020-05-18 10:25 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/metatype/TmetadataImplTest.java
> +        assertEquals(designate, tmetadata.getDesignate());
While using `assertEquals`, `assertNotEquals` (and so on) they al support a message linked to the `assert*` as a first argument. It is a good practice to add a message that shows which specific assert has failed.

So in this case:
`assertEquals("tmetadata.designate", designate, tmetadata.getDesignate());`
would make any failure linked to a meaningful message which can avoid to have to look at the code to check what has failed.

2020-05-19 07:23 UTC, code-incubus commented
Hi @Coduz,
I made all the changes that you mentioned above. If something is not ok please let me know.
I'll fix it up quickly.

2020-05-19 09:01 UTC, LeoNerdoG approved these changes

2020-05-19 09:03 UTC, LeoNerdoG commented
Hey @Coduz,
now this PR looks ok, I think this can be merged.

2020-05-19 12:00 UTC, Coduz approved these changes

2020-05-19 14:56 UTC, Coduz approved these changes

2020-05-19 14:56 UTC, merged