Fixed cucumber unit tests for Device
eclipse-kapua/kapua pull request #2984
Opened 2020-05-21 10:09 UTC by code-incubus

**Signed-off-by:** code-incubus nemanja.milutinovic@comtrade.com

Fixed unit tests for Device and added new test scenarios for clientID validation.

**Related Issue:**
#2811 

**Description of the solution adopted:**
Test scenarios that are added in this PR are checking functionalities regarding Device. All-new scenarios are added to DeviceRegistry.feature. Scenarios are testing if Device ID is correctly created, edited, or deleted. Also, I've added _@Inject_ annotations at DeviceEventServiceImpl.java.

_Another small change (removing commented feature file ) is at runner class for job service unit tests._

**Screenshots**
/

**Any side note on the changes made**
/

2020-05-25 10:32 UTC, LeoNerdoG requested changes
Hey @code-incubus,
I have reviewed this PR and I have couple of remarks - can you please update the branch when you finish? Thanks!

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    public void iUpdateTheDeviceClientIDFromToNewClientId(String oldClientId, String newClientId) throws Exception {
Please change the method name to: "iUpdateTheDeviceClientIDToNewClientId"

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    @Given("^I create device with null clientID$")
Please change step name to: "@Given("^I create a device with null clientID$")"

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +    public void iCreateDeviceWithNullClientID() throws Throwable{
Please change the method name to: "iCreateADeviceWithNullClientID"

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/java/org/eclipse/kapua/service/device/registry/test/CucumberWithPropertiesForDeviceRegistry.java
> +
Please delete this empty line.

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceEvent.feature
>      exception must be thrown.
Please change the description to: "Counting events in an empty (non existing) scope must return a count of 0. No exception should be thrown."

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        Then Named device registry searches are case sensitive
Can you please change the name of this step, because it is not clear what it does...?

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        When I search for a device with a random ID
Can you please change the name of this step to: "When I search for a device with a nonexisting registry ID"

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        When I search for a device with a random client ID
Can you please change the name of this step to: "When I search for a device with a nonexisting client ID"

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        And I extract the first device
Please change the step name to: "And I extract the device with correct BIOS version"

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        When I query for devices with Client Id "TestDevice"
Why do you query for this device here? Is this relavant?

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        Then The client ID was not changed
Please change or reuse one of the previous steps ("Then I tryi to find device with ID.."). Just checking in the background if this has been done or not is not enough.

2020-05-25 10:32 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +        When I delete a device with random IDs
Can you please change the name of this step to: "When I delete a device with nonexisting ID"

2020-05-25 11:24 UTC, LeoNerdoG requested changes
Hey @code-incubus,
I just noticed that there are some problems with the headers. 
You shouldn't just delete the original year and switch it with new one. The convention here is that the first year is the yer of first implementation and second is the year of last change. 
So if file is originally from 2017 and you have modified it, the copyright has to be: 

"I see this only now - please change header to " * Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others""

If the file is new, there is only one year, the current one: 

"I see this only now - please change header to " * Copyright (c) 2020 Eurotech and/or its affiliates and others""

Please address these changes and then we are good to go 😺

2020-05-25 11:24 UTC, LeoNerdoG commented on service/device/registry/test/src/test/java/org/eclipse/kapua/service/device/registry/test/CucumberWithPropertiesForDeviceRegistry.java
> + * Copyright (c) 2020 Eurotech and/or its affiliates and others
I see this only now - please change header to " * Copyright (c) 2019, 2020 Eurotech and/or its affiliates and others"

2020-05-25 11:24 UTC, LeoNerdoG commented on service/device/registry/test/src/test/java/org/eclipse/kapua/service/device/registry/test/RunDeviceRegistryUnitTest.java
> + * Copyright (c) 2020 Eurotech and/or its affiliates and others
I see this only now - please change header to " * Copyright (c) 2019, 2020 Eurotech and/or its affiliates and others"

2020-05-25 11:24 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistryConnection.feature
> +# Copyright (c) 2020 Eurotech and/or its affiliates and others
I see this only now - please change header to " * Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others"

2020-05-25 11:24 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistryValidation.feature
> +# Copyright (c) 2020 Eurotech and/or its affiliates and others
I see this only now - please change header to " * Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others"

2020-05-25 11:24 UTC, LeoNerdoG commented on service/device/registry/test/src/test/resources/features/DeviceRegistry.feature
> +# Copyright (c) 2020 Eurotech and/or its affiliates and others
I see this only now - please change header to " * Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others"

2020-05-25 13:28 UTC, LeoNerdoG approved these changes

2020-05-25 13:29 UTC, LeoNerdoG commented
Hey @Coduz,
I have reviewed this PR and it looks good. All the tests have passe, codeCov is green - can you merge this please?

2020-05-26 12:34 UTC, Coduz approved these changes

2020-05-26 12:34 UTC, merged