Added Junit Tests for LocalCache Class
eclipse-kapua/kapua pull request #3014
Opened 2020-07-06 09:26 UTC by sonja-ct

Added Junit Tests for LocalCache Class

Signed-off-by: Sonja <sonja.matic@comtrade.com>

Brief description of the PR.
/

**Related Issue**
/
**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-07-13 12:20 UTC, LeoNerdoG approved these changes
hey @Coduz,
I have checked this PR and it looks OK - can you please check it when you have time and merge?

2020-07-24 08:23 UTC, Coduz requested changes
I made some comments on things which I have already commented on #3008.
All other things are good :)

2020-07-24 08:23 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/cache/LocalCacheTest.java
> +                    assertNotNull(localCache);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:23 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/cache/LocalCacheTest.java
> +                    assertThat("LocalCache object expected.", localCache, IsInstanceOf.instanceOf(LocalCache.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:23 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/cache/LocalCacheTest.java
> +                assertNotNull("Null not expected.", localCache);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:23 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/cache/LocalCacheTest.java
> +                assertThat("LocalCache object expected.", localCache, IsInstanceOf.instanceOf(LocalCache.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-29 11:01 UTC, sonja-ct commented
Hey @Coduz,
I made all the requested changes, if you can take a look, I hope everything is ok now.
Thanks, Sonja

2020-09-02 08:43 UTC, Coduz approved these changes

2020-09-02 13:33 UTC, merged