Added Junit Tests
eclipse-kapua/kapua pull request #3015
Opened 2020-07-06 10:02 UTC by sonja-ct

Added Junit tests for AboutEntry class
Added Junit tests for AboutScanner class
Added Junit tests for EventStoreQueryImpl class
Added Junit tests for EventStoreRecordCreatorImpl class
Added Junit Tests for EntityCache class
Added Junit Tests for KapuaCacheManager class
Added Junit Tests for NamedEntityCache class

Signed-off-by: Sonja <sonja.matic@comtrade.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-07-22 07:48 UTC, LeoNerdoG approved these changes
Hey @Coduz,
I have checked this PR and it looks Ok. Can you go through and merge it when you have time? Thanks!

2020-07-24 08:48 UTC, Coduz requested changes

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/about/AboutEntryTest.java
> +                    assertNotNull("Null not expected.", license);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/about/AboutEntryTest.java
> +                    assertThat("AboutEntry.License object expected.", license, IsInstanceOf.instanceOf(AboutEntry.License.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/about/AboutScannerTest.java
> +        assertNotNull("Null not expected", scanner);
For example in this case this makes sense.
There is no `new` and `AboutScanner.scan()` can return `null` even if is not designed to, if someone changes the implementation of `scan()`

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
> +        assertNotNull("Null not expected.", eventStoreQueryImpl);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
> +        assertThat("EventStoreQueryImpl object expected.", eventStoreQueryImpl, IsInstanceOf.instanceOf(EventStoreQueryImpl.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
> +        assertNotNull("Null not expected.", eventStoreQueryImpl1);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
> +        assertThat("EventStoreQueryImpl object expected.", eventStoreQueryImpl1, IsInstanceOf.instanceOf(EventStoreQueryImpl.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
> +            assertNotNull("Null not expected.", eventStoreQueryImpl2);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreQueryImplTest.java
> +            assertThat("EventStoreQueryImpl object expected.", eventStoreQueryImpl2, IsInstanceOf.instanceOf(EventStoreQueryImpl.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreRecordCreatorImplTest.java
> +        KapuaId[] scopeIdList = {null, new KapuaIdStatic(BigInteger.ONE), new KapuaIdStatic(BigInteger.TEN), new KapuaIdStatic(BigInteger.ZERO)};
Same as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R103

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreRecordCreatorImplTest.java
> +            assertNotNull("Null not expected.", eventStoreRecordCreatorImpl);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/event/store/internal/EventStoreRecordCreatorImplTest.java
> +            assertThat("EventStoreRecordCreatorImpl object expected.", eventStoreRecordCreatorImpl, IsInstanceOf.instanceOf(EventStoreRecordCreatorImpl.class));
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-24 08:48 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/service/internal/cache/EntityCacheTest.java
> +        assertNotNull(entityCache);
Same things as #3008 - https://github.com/eclipse/kapua/pull/3008/files#diff-031d59073d14c177c331d7ce9d2a83d8R67

2020-07-29 10:23 UTC, sonja-ct commented
Hey @Coduz,
I made all the requested changes, if you can take a look, I hope everything is ok now. 
Thanks, Sonja

2020-09-11 12:28 UTC, Coduz approved these changes

2020-09-11 12:28 UTC, merged