Set with the same digits of precision for mysql timestamp default val…
eclipse-kapua/kapua pull request #3023
Opened 2020-07-11 07:11 UTC by miricy

…ue #2991

Signed-off-by: alva.huang <alva@izhiju.cn>

2020-07-13 06:22 UTC, LeoNerdoG requested changes
Hey @miricy,
there are some headers to be changed. Please take a look.

2020-07-13 06:22 UTC, LeoNerdoG commented on commons/src/main/resources/liquibase/common-properties.xml
> +    <property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
Pleae change the header to: 
<!--
    Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    Contributors:
        Eurotech - initial API and implementation
 -->

2020-07-13 06:22 UTC, LeoNerdoG commented on service/account/internal/src/main/resources/liquibase/common-properties.xml
> +    <property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
Pleae change the header to: 
<!--
    Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    Contributors:
        Eurotech - initial API and implementation
 -->

2020-07-13 06:22 UTC, LeoNerdoG commented on service/device/registry/internal/src/main/resources/liquibase/common-properties.xml
> +    <property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
Pleae change the header to: 
<!--
    Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    Contributors:
        Eurotech - initial API and implementation
 -->

2020-07-13 06:22 UTC, LeoNerdoG commented on service/endpoint/internal/src/main/resources/liquibase/common-properties.xml
> +    <property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
Pleae change the header to: 
<!--
    Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    Contributors:
        Eurotech - initial API and implementation
 -->

2020-07-13 06:22 UTC, LeoNerdoG commented on service/tag/internal/src/main/resources/liquibase/common-properties.xml
> +    <property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
Pleae change the header to: 
<!--
    Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    Contributors:
        Eurotech - initial API and implementation
 -->

2020-07-13 06:22 UTC, LeoNerdoG commented on service/user/internal/src/main/resources/liquibase/common-properties.xml
> +    <property name="now" value="current_timestamp(3)" dbms="mysql,mariadb,h2"/>
Pleae change the header to: 
<!--
    Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    Contributors:
        Eurotech - initial API and implementation
 -->

2020-07-13 12:50 UTC, miricy commented
@LeoNerdoG Do you mean to complete the title and description， Whats the header to be change

2020-07-13 12:52 UTC, LeoNerdoG commented
Oh, I can see just now that Github did not parse my message correctly. 
Please change the year of the last modification of the file, so instead of only "2017", let it be "2017, 2020" (the first year is the year of the initial commit and the latter one is the year of the last change).

2020-07-15 10:23 UTC, Coduz commented
Hi @miricy ,

thanks for the submission. 
I've tested this against also other DB and is working fine.
You may want to add your name to the Contributor in the header of the files? 

Like:
```
/*******************************************************************************
 * Copyright (c) 2017, 2020 Eurotech and/or its affiliates and others
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Eurotech - initial API and implementation
 *     <your name> - <your email>
 *******************************************************************************/
```

Regards, 

- Alberto

2020-07-17 04:48 UTC, miricy commented
Hi @Coduz  
Well, I've learned too much from this project, and I'm very happy to be able to help a little bit with this project。

2020-07-17 15:41 UTC, Coduz commented
Hi @miricy ,

We also like contributions! 
Thanks! 

This will be merged now and will be backported in `release-1.2.x` and released with  Kapua `1.2.5`.

Regards, 

_Alberto_

2020-07-17 15:42 UTC, merged