Added JUnit for commons package and I9 tests for Translator
eclipse-kapua/kapua pull request #3029
Opened 2020-07-20 08:12 UTC by code-incubus

**Signed-off-by:** code-incubus nemanja.milutinovic@comtrade.com

Added JUnit tests for the common package, also added new tests for the translator.

**Related Issue:**
/ 

**Description of the solution adopted:**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-07-22 07:48 UTC, LeoNerdoG approved these changes
Hey @Coduz,
I have checked this PR and it looks Ok. Can you go through and merge it when you have time? Thanks!

2020-07-24 09:31 UTC, Coduz requested changes
I've added some request changes on the usage of `assertTrue` with conditions with `.equals`
I've also need to check why some of the error messages are do not contain a meaning full message

2020-07-24 09:31 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +            assertTrue("Expected and actual values should be the same!", kapuaSettingException.getCode().toString().equals("INVALID_RESOURCE_NAME") && kapuaSettingException.getMessage().equals("Error
Please split this into 2 assertEquals otherwise the real cause of the assertFailure will be hidden and uncertain.

2020-07-24 09:31 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +        assertTrue("Expected and actual values should be the same!", kapuaSettingException.getCode().toString().equals("INVALID_RESOURCE_NAME") && kapuaSettingException.getMessage().equals("Error: "
Please split this into 2 assertEquals otherwise the real cause of the assertFailure will be hidden and uncertain.

2020-07-24 09:31 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +        assertTrue("Expected and actual values should be the same!", kapuaSettingException.getCode().toString().equals("INVALID_RESOURCE_NAME") && kapuaSettingException.getCause().equals(throwable) &
Please split this into 2 assertEquals otherwise the real cause of the assertFailure will be hidden and uncertain.

2020-07-24 09:31 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +        assertTrue("Expected and actual values should be the same!", kapuaSettingException.getCode().toString().equals("INVALID_RESOURCE_NAME") && kapuaSettingException.getCause() == null && kapuaSet
Please split this into 2 assertEquals otherwise the real cause of the assertFailure will be hidden and uncertain.

2020-07-24 09:31 UTC, Coduz commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +            assertTrue("Expected and actual values should be the same!", kapuaSettingException.getCode().toString().equals("INVALID_RESOURCE_NAME") && kapuaSettingException.getCause().equals(throwabl
Please split this into 2 assertEquals otherwise the real cause of the assertFailure will be hidden and uncertain.

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    And I expect the exception "InvalidMessageException" with the text "Invalid message: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    When I try to translate kura data message to mqtt message
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    And I expect the exception "InvalidChannelException" with the text "Invalid channel: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    And I expect the exception "InvalidMessageException" with the text "Invalid message: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Then I expect the exception "InvalidMessageException" with the text "Invalid message: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Then I expect the exception "InvalidPayloadException" with the text "Invalid payload: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Then I expect the exception "InvalidChannelException" with the text "Invalid channel: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-07-24 09:31 UTC, Coduz commented on translator/test/src/test/resources/features/TranslatorUnitTests.feature
> +    Then I expect the exception "InvalidMessageException" with the text "Invalid message: null"
Maybe this is something I need  to check. 
There should be a meaningful message

2020-09-04 11:30 UTC, LeoNerdoG commented
hey @code-incubus,
there are some conflicts that have to be resolved and also some comments to be addressed. Can you please fix this?

2020-09-07 12:07 UTC, code-incubus commented
Hi @Coduz, I have made changes for unit tests. Please let me know If needs any changes regards meaningful messages for cucumber integration tests.

2020-09-11 12:37 UTC, Coduz approved these changes

2020-09-11 12:38 UTC, merged