Added Unit Tests For Configuration Module
eclipse-kapua/kapua pull request #3039
Opened 2020-07-28 13:02 UTC by zanpizmoht

Signed-off-by: zanpizmoht <zan.pizmoht@comtrade.com>

In this PR unit tests for Configuration module are added.

**Related Issue**
None

**Description of the solution adopted**
I added unit tests for all the classes that are in commons/configuration module.

2020-09-02 08:52 UTC, LeoNerdoG requested changes
Hey @zanpizmoht,
I have reviewed this branch and there are some minor things to be fixed. 
Please rebase this PR on develop, as it is not up-to-date.

2020-09-02 08:52 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/KapuaConfigurableServiceSchemaUtilsTest.java
> +    }
Please add additional tests for DropSchemaObjects method (for now we have default, empty, null and wrong, but we also need some custom strings to be tested).

2020-09-02 08:52 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/KapuaConfigurableServiceSchemaUtilsTest.java
> +
Please add additional tests for CreateSchemaObjects method (for now we have default, empty, null and wrong, but we also need some custom strings to be tested)

2020-09-02 08:52 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceComponentConfigurationImplTest.java
> +    @Test
I think this test is obsolete, it is basically a copy of:

   @Test
    public void getIdIfIsSetTest() {
        serviceComponentConfiguration.setId("1");
        assertEquals(serviceComponentConfiguration.getId(), "1");
    }

2020-09-02 08:52 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceComponentConfigurationImplTest.java
> +    @Test
I think this test is obsolete, it is basically a copy of:
    @Test
    public void setNameIfNotNullTest() {
        serviceComponentConfiguration.setName("name");
        assertEquals(serviceComponentConfiguration.getName(), "name");
    }

2020-09-02 08:52 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/configuration/ServiceComponentConfigurationImplTest.java
> +        properties.put("property1", 10);
Cna we please try with different objects rather than just Integer?

2020-09-09 06:57 UTC, zanpizmoht commented
Hey @LeoNerdoG, I have modified tests as you suggested and it should now be ready for merge :)

2020-09-09 12:28 UTC, LeoNerdoG approved these changes

2020-09-11 13:18 UTC, Coduz approved these changes

2020-09-11 15:14 UTC, merged