Restore @Path in DeviceManagementOperations REST APIs
eclipse-kapua/kapua pull request #3040
Opened 2020-07-29 14:59 UTC by lorthirk

In #2795 `{scopeId}/devices/{deviceId}/operations` and `{scopeId}/devices/{deviceId}/operations/{operationId}/notifications` were inadvertently removed. This is to restore them. 

**Related Issue**
No related issues

2020-07-30 05:49 UTC, LeoNerdoG requested changes
Hey @lorthirk,
please update the headers in the edited files.

2020-07-30 05:49 UTC, LeoNerdoG commented on rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperationNotifications.java
> +@Path("{scopeId}/devices/{deviceId}/operations/{operationId}/notifications")
Please update header to "2020".

2020-07-30 05:49 UTC, LeoNerdoG commented on rest-api/resources/src/main/java/org/eclipse/kapua/app/api/resources/v1/resources/DeviceManagementOperations.java
> +@Path("{scopeId}/devices/{deviceId}/operations")
Please update header to "2020".

2020-08-28 09:57 UTC, Coduz approved these changes

2020-08-28 10:46 UTC, merged