Added Junit Tests
eclipse-kapua/kapua pull request #3070
Opened 2020-09-14 07:09 UTC by sonja-ct

Added Junit tests for service/api/service/config package
Added Junit tests for service/stream/api package

Added Junit tests for DeviceMenagmentException class
Added Junit tests for KapuaDuplicateExternalIdException class
Added Junit tests for KapuaDuplicateExternalIdInAnotherAccountError
class
Added Junit tests for KapuaDuplicateNameException class
Added Junit tests for KapuaDuplicateNameInAnotherAccountError class
Added Junit tests for KapuaEndBeforeStartTimeException class
Added Junit tests for KapuaEntityNotFoundException class

Signed-off-by: Sonja <sonja.matic@comtrade.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-09-15 06:46 UTC, LeoNerdoG requested changes
Hey @sonja-ct,
I have checked this PR and for most part it looks ok, there are some for loops to be enhanced and some branches are not covered one of the classes, please take a look. 
Thanks!

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/KapuaDuplicateExternalIdExceptionTest.java
> +        for (int i = 0; i < duplicatedExternalId.length; i++) {
Pleas use enhanced for loop (example: for(String string: duplicatedExternalId)

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/KapuaDuplicateExternalIdInAnotherAccountErrorTest.java
> +    public void kapuaDuplicateExternalIdInAnotherAccountErrorTest() {
Pleas use enhanced for loop (example: for(String string: duplicatedExternalId)

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Long[] longArray = {10L, 20L, 20200L};
Please add "null" as parameter, otherwise you will not cover lin 85 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Double[] doubleArray = {10.123d, 1000.1234556d, 10.100000000000000000000d};
Please add "null" as parameter, otherwise you will not cover lin 96 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Float[] floatArray = {10.100000000000000000000f, 1010101010.10f, 1010101010.1f};
Please add "null" as parameter, otherwise you will not cover lin 107 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Integer[] integerArray = {-2000, -20, 0, 10, 20,};
Please add "null" as parameter, otherwise you will not cover lin 118 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Byte[] byteArray = {-128, -10, 0, 10, 127};
Please add "null" as parameter, otherwise you will not cover lin 129 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Character[] characterArray = {'c', 'h', 'a', 'r', 'a', 'c', 't', 'e', 'r'};
Please add "null" as parameter, otherwise you will not cover lin 140 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Boolean[] booleanArray = {true, false};
Please add "null" as parameter, otherwise you will not cover lin 151 in the tested class.

2020-09-15 06:46 UTC, LeoNerdoG commented on service/api/src/test/java/org/eclipse/kapua/service/config/ServiceXmlConfigPropertiesAdapterTest.java
> +        Short[] shortArray = {-32768, 1, 0, 10, 32767};
Please add "null" as parameter, otherwise you will not cover lin 162 in the tested class.

2020-09-16 06:09 UTC, LeoNerdoG commented
Hey @Coduz,
I have reviewed this PR and it looks OK. Travis is green and coverage increased, can you please take a look at this and merge when you can? 
Thanks!

2020-09-16 06:11 UTC, LeoNerdoG approved these changes

2020-09-18 09:54 UTC, Coduz approved these changes

2020-09-18 09:55 UTC, merged