Added Junit tests in commons/util and commons/setting packages
eclipse-kapua/kapua pull request #3083
Opened 2020-09-29 10:11 UTC by sonja-ct

Added Junit tests in commons module:

util package:
ClassUtil class
KapuaFileUtils class
SemanticVersion class
StringUtil class

setting package:
AbstractKapuaSetting class
EnvFriendlyConfiguration class
KapuaSettingException class
SimpleSettingKey class
SystemSettingKey class

Signed-off-by: Sonja <sonja.matic@comtrade.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-09-29 11:38 UTC, LeoNerdoG requested changes
Hey @sonja-ct,
i have reviewed the branch and it seems OK, there are only some minor issues to be fixed. I have also commented that some tests have to be added. Please try to add new tests but don't exceed 1k lines.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
Please delete this empty line.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
>          // Given
Please delete all these annotations since I think they are not needed.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
>          // Then
Please delete all these annotations since I think they are not needed.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
>          // Given
Please delete all these annotations since I think they are not needed.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
>          // When
Please delete all these annotations since I think they are not needed.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
>          // Then
Please delete all these annotations since I think they are not needed.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractKapuaSettingTest.java
> +}
Please add tests for:
 - createCompositeSource
 - loadConfigResources
 - loadConfigResource
classes, as they are not covered with tests.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/EnvFriendlyConfigurationTest.java
> +    public void createInstanceOfClass() {
Please move lines with: 
    CompositeConfiguration compositeConfiguration;
    EnvFriendlyConfiguration envFriendlyConfiguration;
to lines 23, 24, so they are before "@Before public void createInstanceofClass()" method.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/EnvFriendlyConfigurationTest.java
> +        assertFalse("The key is contained!", envFriendlyConfiguration.containsKey("Key"));
Please change message from "The key is not contained" to "There is no key!"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/EnvFriendlyConfigurationTest.java
> +        assertTrue("The key is not contained!", envFriendlyConfiguration.containsKey("Key"));
Please change message from "The key is not contained" to "There is no key!"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/EnvFriendlyConfigurationTest.java
> +        assertFalse("The key is contained!", envFriendlyConfiguration.containsKey("Key"));
Please change message from "The key is not contained" to "There is no key!"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/EnvFriendlyConfigurationTest.java
> +        assertTrue("The key is not contained!", envFriendlyConfiguration.containsKey("key.property"));
Please change message from "The key is not contained" to "There is no key!"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +    public void throwingKapuaSettingExceptionKapuaSettingErrorCodesTest() throws KapuaSettingException {
Please rename this test to: "throwingKapuaSettingErrorCodes"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +    public void throwingKapuaSettingExceptionKapuaSettingErrorCodesArgumentsTest() throws KapuaSettingException {
Please rename this test to: "throwingKapuaSettingErrorCodesWithArguments"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/KapuaSettingExceptionTest.java
> +    public void throwingKapuaSettingExceptionKapuaSettingErrorCodesCauseArgumentsTest() throws KapuaSettingException {
Please rename this test to: "throwingKapuaSettingErrorCodesWithCauseAndArguments"

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/util/SemanticVersionTest.java
> +    //(expected = NullPointerException.class)
Please delete this line.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/util/SemanticVersionTest.java
> +
Please delete empty line.

2020-09-29 11:38 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/util/SemanticVersionTest.java
> +
Please delete empty line.

2020-09-29 12:56 UTC, sonja-ct commented
Hey @LeoNerdoG , I have made the requested changes, I hope everything is ok now :)

2020-09-29 13:06 UTC, LeoNerdoG approved these changes
@sonja-ct All good! 😄 
@Coduz I have checked this PR and it looks OK! 
Can you please take a look and merge it when CI passes? Thanks!

2020-10-07 08:32 UTC, Coduz approved these changes

2020-10-07 08:33 UTC, merged