Added Junit tests in commons/setting package
eclipse-kapua/kapua pull request #3084
Opened 2020-09-29 11:07 UTC by sonja-ct

Added Junit tests in commons/setting package for:
AbstractBaseKapuaSetting class
SystemSetting class

Signed-off-by: Sonja <sonja.matic@comtrade.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-09-29 12:35 UTC, LeoNerdoG requested changes
hej @sonja-ct,
I have reviewed this PR and it looks OK, there are only few minor things that need to be changed/added (mostly assertions in some methods) and some lines to be deleted. 
Please take a look 😄

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.get(null, key);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.get(String.class, null);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.get(null, key, 10);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.get(String.class, null, 10);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getList(null, key);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getList(String.class, null);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getMap(String.class, null, "Key");
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getMap(String.class, null);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(null);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(key);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(key);
Please add assertion here (i guess assertNull)?

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(key, null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(null, 10);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(key, (Integer) null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getInt(null, (Integer) 10);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getBoolean(null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getBoolean(key, null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getBoolean(null, true);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getBoolean(key, (Boolean) null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getBoolean(null, (Boolean) true);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getString(null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getString(null, "Value");
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getLong(null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getLong(null, 10L);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getLong(key, null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getFloat(null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getLong(null, (Long) 10L);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getLong(key, (Long) null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getFloat(null, 10.11f);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getFloat(key, null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getFloat(null, (Float) 10.11f);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getFloat(key, (Float) null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getDouble(null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getDouble(null, 10.11);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getDouble(key, null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getDouble(null, (Double) 10.11);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.getDouble(key, (Double) null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +        abstractBaseKapuaSetting.setSystemPropertyHotSwap((Boolean) null);
Please add assertion here.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/system/SystemSettingTest.java
> +
Please delete empty line.

2020-09-29 12:35 UTC, LeoNerdoG commented on commons/src/test/java/org/eclipse/kapua/commons/setting/AbstractBaseKapuaSettingTest.java
> +
Please delete empty line.

2020-09-29 13:16 UTC, LeoNerdoG approved these changes
Hey @Coduz,
I have checked this PR and it looks OK, can you please merge it when CI passes? 
Thanks!

2020-10-07 08:26 UTC, Coduz approved these changes

2020-10-07 08:30 UTC, merged