Added cucumber unit tests for service/tag package
eclipse-kapua/kapua pull request #3097
Opened 2020-10-08 09:54 UTC by VesnaGrumic

Added Cucumber unit tests for service/tag

Signed-off-by: VesnaGrumic <vesna.grumic@endava.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-10-08 10:00 UTC, LeoNerdoG requested changes
Hey @VesnaGrumic,
can you please move the "List" import back where it was - see comment below). 
Thanks! Everything else is OK, so @Coduz you can merge it when all the checks complete. 

We moved the tag CRUD tests from qa integration to service, that's why the file has been deleted.

2020-10-08 10:00 UTC, LeoNerdoG commented on service/device/registry/test-steps/src/main/java/org/eclipse/kapua/service/device/registry/steps/DeviceRegistrySteps.java
> +import java.util.List;
can you please put this import back, there is no need to move it two lines down 😄

2020-10-08 18:50 UTC, LeoNerdoG approved these changes

2020-10-08 19:16 UTC, LeoNerdoG commented
Hey @Coduz,
I have checked this PR and it looks good. Can you please review and merge it when you have time? Thanks!

2020-10-09 07:52 UTC, Coduz approved these changes

2020-10-09 09:35 UTC, merged