Added JUnit tests for provider package
eclipse-kapua/kapua pull request #3103
Opened 2020-10-13 11:17 UTC by VesnaGrumic

Added JUnit tests for FuseChannel class
Added JUnit tests for Callbacks class
Added JUnit tests for AbstractMqttChannel class
Added JUnit tests for Listeners class

Signed-off-by: VesnaGrumic <vesna.grumic@endava.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-10-13 11:23 UTC, LeoNerdoG approved these changes
Hey @Coduz,
I have checked this PR and it looks OK. can you please emrge it after CI finishes? Thanks! 
P.S. Please add label "test" to the PR.

2020-11-12 12:58 UTC, Coduz requested changes
Hi @VesnaGrumic 

also this PR has the same problems as #3104 

So please fix the usase of `expected` or `assert*`.

Thanks,

_Alberto_

2020-11-12 12:58 UTC, Coduz commented on client/gateway/provider/fuse/src/test/java/org/eclipse/kapua/client/gateway/mqtt/fuse/FuseChannelTest.java
> +    @Test(expected = NoClassDefFoundError.class)
Same as comments on #3104

2020-11-12 12:58 UTC, Coduz commented on client/gateway/provider/fuse/src/test/java/org/eclipse/kapua/client/gateway/mqtt/fuse/FuseChannelTest.java
> +    public void publishMqttTest() throws Exception {
This is a correct usage of `expected`

2021-01-13 09:27 UTC, closed without merging