Added JUnit tests
eclipse-kapua/kapua pull request #3104
Opened 2020-10-13 11:22 UTC by VesnaGrumic

Added JUnit tests for DefaultClient class
Added JUnit tests for DefaultApplication class
Added JUnit tests for DefaultData class

Signed-off-by: VesnaGrumic <vesna.grumic@endava.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2020-10-13 11:23 UTC, LeoNerdoG approved these changes
Hey @Coduz,
I have checked this PR and it looks OK. can you please emrge it after CI finishes? Thanks! 
P.S. Please add label "test" to the PR.

2020-11-12 12:54 UTC, Coduz requested changes
Hi @VesnaGrumic 

I've made a comment on one of the test because it is not the correct way of testing throwing of exception. 

There are many places in which that is done, so please check 'em all!

Thanks

_Alberto_

2020-11-12 12:54 UTC, Coduz commented on client/gateway/spi/src/test/java/org/eclipse/kapua/client/gateway/spi/DefaultClientTest.java
> +    public void defaultClientChannelNullTest() {
Please check this.
The test is either expected to throw NPE or perform the last `.assertEquals`.
In the first case `assertEquals` should be removed and let just the NPE happen

2020-12-16 08:46 UTC, lorthirk commented
Superseded by #3150

2020-12-16 08:46 UTC, closed without merging