Extend accountSelfEdit support in Configurations
eclipse-kapua/kapua pull request #3152
Opened 2020-11-24 17:37 UTC by lorthirk

Extending support for `allowSelfEdit` in Service configurations. A field marked with `allowSelfEdit="true"` in the Service Metadata XML can be edited by users of the account itself, not only from the parent account. As a first use case, all the configurations of `CredentialsService` are now self-editable.

An user can edit its own `allowSelfEdit="true"` configurations in the "Settings" view of the console, or via REST API.

**Related Issue**
No related issues

2020-11-25 11:52 UTC, LeoNerdoG requested changes
Hey @lorthirk,
I have checked this PR and it all looks fine except the message as commented bellow and this permission error. I think that it should be handled more gracefuly? What do you think?

![Screenshot 2020-11-25 at 07 46 13](https://user-images.githubusercontent.com/15121999/100224317-f6bb6c80-2f1c-11eb-987f-4144c919632c.png)

2020-11-25 11:52 UTC, LeoNerdoG commented on commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableService.java
> +                throw KapuaException.internalError(String.format("The configuration \"%s\" cannot be changed from an user of the account", ad.getId()));
I think that this message should be "The configuration \"%s\" cannot be changed by this user in this account" or something similar. What do you think?

2020-11-26 09:17 UTC, lorthirk commented on commons/src/main/java/org/eclipse/kapua/commons/configuration/AbstractKapuaConfigurableService.java
> +                throw KapuaException.internalError(String.format("The configuration \"%s\" cannot be changed from an user of the account", ad.getId()));
Yes, this could work

2020-11-26 09:19 UTC, lorthirk commented
Well... In a way I agree with you, the error should be handled more gracefully. Anyway this is a general problem of how missing permissions are reported: you will get the same message if, let's say, you go change a setting in a child account for a service you only have a `read` permission. So I wouldn't link the issue to this PR, but rather open a new one for the specific case.

2020-11-26 11:12 UTC, Coduz approved these changes

2020-11-26 11:28 UTC, LeoNerdoG approved these changes

2020-12-11 12:39 UTC, merged