Added JUnit tests for core/exception/model package
eclipse-kapua/kapua pull request #3248
Opened 2021-02-22 13:41 UTC by sonja-ct

This PR contains JUnit tests for classes in exception/model package in
rest-api/core module:
 - IllegalArgumentExceptionInfo class
 - IllegalNullArgumentExceptionInfo class
 - InternalUserOnlyExceptionInfo class
 - MfaRequiredExceptionInfo class
 - SelfManagedOnlyExceptionInfo class
 - SubjectUnauthorizedExceptionInfo class
 - ThrowableInfo class

Signed-off-by: Sonja <sonja.matic@endava.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2021-02-22 13:43 UTC, LeoNerdoG approved these changes
hey @Coduz,
I have checked this PR and it looks OK. This is part of "rest api unit tests" that we have been talking about (achieving code coverage for rest-api module through unit tests). 
After all these PRs are merged and we have framework for Rest Api testing in place, we will add high-level/integration rest api tests, that will check the actual fucntionality. 
Please take a look and merge when you can.

2021-02-26 08:32 UTC, LeoNerdoG approved these changes

2021-03-04 09:55 UTC, Coduz requested changes

2021-03-04 09:55 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/model/MfaRequiredExceptionInfoTest.java
> +        for (KapuaAuthenticationErrorCodes code : errorCodes) {
Why using a for-loop with `@Test(expected = NullPointerException.class)`?

2021-03-04 09:55 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/model/MfaRequiredExceptionInfoTest.java
> +        for (Response.Status status : statusList) {
Why using a for-loop with `@Test(expected = NullPointerException.class)`?

2021-03-05 06:39 UTC, sonja-ct commented
Hey @Coduz I made requested changes, so you can merge this when you have time. Thanks

2021-04-23 15:21 UTC, merged