Added JUnit tests for exception and model packages
eclipse-kapua/kapua pull request #3251
Opened 2021-02-22 13:52 UTC by sonja-ct

This PR JUnit tests for classes in exception and model packages in rest-api/resources module:

 - exception package:
RestApiRuntimeException class
SessionNotPopulatedException class

- model package
ByteArrayParam class
CountResult class
DateParam class
EntityId class
MetricType class
ScopeId class
StorableEntityId class

Also it contains JUnit tests for class AbstractKapuaResource.

Signed-off-by: Sonja <sonja.matic@endava.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2021-02-22 13:54 UTC, LeoNerdoG approved these changes
hey @Coduz,
I have checked this PR and it looks OK. This is part of "rest api unit tests" that we have been talking about (achieving code coverage for rest-api module through unit tests).
After all these PRs are merged and we have framework for Rest Api testing in place, we will add high-level/integration rest api tests, that will check the actual fucntionality.
Please take a look and merge when you can.

2021-02-26 08:31 UTC, LeoNerdoG approved these changes

2021-03-04 09:10 UTC, Coduz requested changes

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/RestApiRuntimeExceptionTest.java
> +            assertEquals("NullPointerException expected.", new NullPointerException().toString(), e.toString());
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/RestApiRuntimeExceptionTest.java
> +            assertEquals("NullPointerException expected.", new NullPointerException().toString(), e.toString());
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/exception/RestApiRuntimeExceptionTest.java
> +            assertEquals("NullPointerException expected.", new NullPointerException().toString(), e.toString());
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/DateParamTest.java
> +            Assert.assertTrue("True expected", dateParam.getDate() instanceof Date);
DateParam.getDate() returns a Date.
So this is always true

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/DateParamTest.java
> +    public void dateParamNullTest() throws KapuaIllegalArgumentException {
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/DateParamTest.java
> +    public void dateParamInvalidDateTest() throws KapuaIllegalArgumentException {
This is the correct way of expecting exception in a test! 😁

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/EntityIdTest.java
> +            Assert.assertEquals("NullPointerException expected.", new NullPointerException().toString(), e.toString());
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 09:10 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/ScopeIdTest.java
> +            Assert.assertEquals("NullPointerException expected.", new NullPointerException().toString(), e.toString());
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 12:34 UTC, LeoNerdoG approved these changes

2021-03-05 06:41 UTC, sonja-ct commented
Hey @Coduz I made requested changes, so you can merge this when you have time. Thanks

2021-03-05 06:42 UTC, sonja-ct commented
Hey @Coduz I made requested changes, so you can merge this when you have time. Thanks

2021-04-23 15:22 UTC, merged