Added JUnit tests for device/management and message packages
eclipse-kapua/kapua pull request #3252
Opened 2021-02-22 13:52 UTC by sonja-ct

This PR contains JUnit tests for classes in rest-api/resources module:

 - device/management package:
   JsonGenericRequestMessage class
   JsonGenericResponseMessage class

 - message package:
   JsonKapuaPayload class

Signed-off-by: Sonja <sonja.matic@endava.com>

**Related Issue**
/

**Description of the solution adopted**
/

**Screenshots**
/

**Any side note on the changes made**
/

2021-02-22 13:54 UTC, LeoNerdoG approved these changes
hey @Coduz,
I have checked this PR and it looks OK. This is part of "rest api unit tests" that we have been talking about (achieving code coverage for rest-api module through unit tests).
After all these PRs are merged and we have framework for Rest Api testing in place, we will add high-level/integration rest api tests, that will check the actual fucntionality.
Please take a look and merge when you can.

2021-02-26 11:23 UTC, LeoNerdoG approved these changes

2021-03-04 09:04 UTC, Coduz requested changes

2021-03-04 09:04 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/device/management/JsonGenericResponseMessageTest.java
> +    public void setAndGetKapuaPayloadTest() {
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 09:04 UTC, Coduz commented on rest-api/core/src/test/java/org/eclipse/kapua/app/api/core/model/device/management/JsonGenericRequestMessageTest.java
> +            Assert.assertEquals("NullPointerException expected.", new NullPointerException().toString(), e.toString());
Please make use of `@Test(expected = NullPointerException.class)`

2021-03-04 12:30 UTC, LeoNerdoG approved these changes

2021-04-23 15:22 UTC, merged