Fixed OpenID Connect tokens  for SSO
eclipse-kapua/kapua pull request #3260
Opened 2021-02-25 10:39 UTC by gbarbon

This PR fixes the OIDC (OpenID Connect) authentication step by using the Id Token instead of the Access Token.

**Related Issue**
Fixes #3257

**Description of the solution adopted**
The OIDC Id Token is now used in place of the Access Token, because the claims that where extracted and/or checked in the Access Token are not always present in it (while they are present in the Id Token). The claims in the Access Token are not defined by the official OIDC specification, thus they change depending on the OIDC Provider. On the other hand, the Id Token claims are precisely defined in the spec.

This PR also uses the `idToken` in place of the `accessToken` in the JUnit tests when needed, and renames all the instances of `jwt` to `accessToken` (since `jwt` was ambiguous).  This PR also renames OIDC env var (see below for further information).

**Screenshots**
_n/a_

**Any side note on the changes made**
This PR also renames OIDC env vars following this schema:
```
OPENID_JWT_ISSUER -> KAPUA_OPENID_JWT_ISSUER
OPENID_CLIENT_ID -> KAPUA_OPENID_CLIENT_ID
CLIENT_SECRET -> KAPUA_OPENID_CLIENT_SECRET
JWT_AUDIENCE -> KAPUA_OPENID_JWT_AUDIENCE
OPENID_AUTH_ENDPOINT -> KAPUA_OPENID_AUTH_ENDPOINT
OPENID_LOGOUT_ENDPOINT -> KAPUA_OPENID_LOGOUT_ENDPOINT
OPENID_TOKEN_ENDPOINT -> KAPUA_OPENID_TOKEN_ENDPOINT
```

2021-03-08 14:02 UTC, lorthirk requested changes

2021-03-08 14:02 UTC, lorthirk commented on plug-ins/sso/openid-connect/api/src/main/java/org/eclipse/kapua/plugin/sso/openid/JwtProcessor.java
> +    String getClaimName();
I would prefer a more descriptive name, since "claim name" is too generic

2021-03-08 14:34 UTC, gbarbon commented on plug-ins/sso/openid-connect/api/src/main/java/org/eclipse/kapua/plugin/sso/openid/JwtProcessor.java
> +    String getClaimName();
Method changed to `getExternalIdClaimName`

2021-03-08 14:59 UTC, lorthirk approved these changes

2021-03-15 09:22 UTC, Coduz approved these changes

2021-03-15 09:23 UTC, merged