External consumers implementation
eclipse-kapua/kapua pull request #3342
Opened 2021-06-30 10:21 UTC by riccardomodanese

Brief description of the PR.
This pr implements the architectural change moving the business logic from the broker to a couple of consumers based on Spring Boot/Camel

**Related Issue**
none

**Description of the solution adopted**
Before this pr the business logic was implemented through Camel routes running inside broker jvm.
Now the telelemetry messages processing logic is moved to a "telemetry" consumer and the lifecycle messages processing logic to a "lifecycle" consumer.
Both consumers are based on Spring Boot, expose health check and metrics through a couple of registered servlet and start the proper Camel routes inside the Camel context.
The standard deployment provide one consumer of both types associated to the broker.

**Screenshots**
none

**Any side note on the changes made**
I'm asking for a deep code review and also a manual test of all the features by reviewers (especially those less covered by unit/integration tests).

2021-07-06 14:48 UTC, lorthirk commented on README.md
> +Suppose the target is the current snapshot 1.6.0-CAMEL-SNAPSHOT.
Correct the Kapua version

2021-07-28 10:45 UTC, Coduz requested changes

2021-07-28 10:45 UTC, Coduz commented on transport/pom.xml
> +        <version>1.6.0-CAMEL-SNAPSHOT</version>
Rename as 1.6.0-SNAPSHOT

2021-07-28 10:45 UTC, Coduz commented on tmpCode/ErrorMessageListener.j
> +/*******************************************************************************
Is this to be removed?

2021-07-28 10:45 UTC, Coduz commented on tmpCode/DataStorageMessageProcessor.java
> +/*******************************************************************************
Is this to be removed?

2021-07-28 10:45 UTC, Coduz commented on service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/mfa/MfaAuthenticatorImplTest.java
> +//    @Test(expected = NullPointerException.class)
Please remove commented tests

2021-07-28 10:45 UTC, Coduz commented on service/security/shiro/src/test/java/org/eclipse/kapua/service/authentication/shiro/mfa/MfaAuthenticatorImplTest.java
> +//    @Test(expected = IllegalArgumentException.class)
Please remove commented tests

2021-07-28 10:45 UTC, Coduz commented on assembly/jetty-base/pom.xml
> +        <jetty.url>https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.39.v20210325/jetty-distribution-9.4.39.v20210325.tar.gz</jetty.url>
Would maybe better to replace with ${jetty.version} ?

2021-08-25 08:01 UTC, Coduz approved these changes

2021-08-26 07:29 UTC, merged