CORS filter is now configurable for users in kapua-sys child account
eclipse-kapua/kapua pull request #3358
Opened 2021-07-21 15:40 UTC by MDeLuise

**Related Issue**
This PR fixes the following problem:
users of one kapua-sys child account cannot configure CORS filters even if they have the permission to do it.

**Description of the solution adopted**
* change the `CorsToolbarGrid`class in order to enable the buttons to add/edit/remove CORS filter correctly
* change the `EndpointInfoServiceImpl` in order to fix the permissions' check
* add integration test regarding CORS filter configuration

2021-08-04 08:43 UTC, lorthirk requested changes

2021-08-04 08:43 UTC, lorthirk commented on service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java
> +        KapuaId scopeIdPermission = entityManagerSession.doAction(em -> EndpointInfoDAO.find(em, scopeId, endpointInfoId))
If `entityManagerSession.doAction(em -> EndpointInfoDAO.find(em, scopeId, endpointInfoId))` returns null, we have a `NullPointerException` here. Let's test this first.

2021-08-04 08:43 UTC, lorthirk commented on service/endpoint/internal/src/main/java/org/eclipse/kapua/service/endpoint/internal/EndpointInfoServiceImpl.java
> +        KapuaId scopeIdPermission = entityManagerSession.doAction(em -> EndpointInfoDAO.find(em, scopeId, endpointInfoId))
If `entityManagerSession.doAction(em -> EndpointInfoDAO.find(em, scopeId, endpointInfoId))` returns null, we have a `NullPointerException` here. Let's test this first.

2021-10-12 15:28 UTC, stefanomorson approved these changes
Looks good to me.

2021-10-12 17:27 UTC, merged