Device Management - move bindings to local module
eclipse-kapua/kapua pull request #3421
Opened 2021-10-25 13:38 UTC by MDeLuise

**Brief description of the PR**
This PR fixes #3416, i.e. move Device Management bindings from the `locator.xml` files to local modules.

**Description of the solution adopted**
* removed all references in the `locator.xml` files regarding device management services and factories
* replaced the deprecated `@KapuaProvider` annotations with the inject annotations `@Singleton`
* created a module, subclass of `AbstractKapuaModule`, in order to bind interfaces and implementations

2021-10-25 14:08 UTC, Coduz approved these changes

2021-10-27 22:21 UTC, stefanomorson requested changes
Not sure DeviceManagementAssetModule is in the correct package
Not sure DeviceManagementCommandBundle is the correct name
Not sure DeviceManagementConfigurationModule is in the correct package

2021-11-02 09:50 UTC, MDeLuise commented
> Not sure DeviceManagementAssetModule is in the correct package Not sure DeviceManagementCommandBundle is the correct name Not sure DeviceManagementConfigurationModule is in the correct package

After the review we had, I implemented the required changes, let me know if there are any missed changes.

2021-11-10 15:33 UTC, Coduz approved these changes

2021-11-11 09:52 UTC, merged