Fix - Updated CORS filtering logic to remove false positives
eclipse-kapua/kapua pull request #3750
Opened 2023-03-23 10:33 UTC by Agnul97

The CORS filtering logic is revisited in order to remove false positives for requests coming from the same origin. The code adapts, with the best effort, to browsers not compatible with the sec-fetch-site header. In fact, in this case, the cors filtering is performed but logically it is impossible to prevent false positives.

2023-03-23 14:02 UTC, Coduz requested changes

2023-03-23 14:02 UTC, Coduz commented on commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
> +            logger.info("<sec-fetch-site> not provided, is the browser incompatible with this header? expect false positives for same origin cors requests filtering");
Promote this to warn level. 
Also, as a general rule, log should provide clear information and logging question does not help much. 
A more useful log line can be as follow:
```
logger.warn("Sec-Fetch-Site' header not present in request: {} {}. CORSResponseFilter may produce false positives for this request. User-Agent is: {}", httpRequest.getMethod(), httpRequest.getPathInfo(), httpRequest.getUserAgent());
```

2023-03-23 14:02 UTC, Coduz commented on commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
> +        String origin = StringUtils.isNotEmpty(httpRequest.getHeader(HttpHeaders.ORIGIN)) ? httpRequest.getHeader(HttpHeaders.ORIGIN) : null;
This is optional, just a personal preference.
For the sake of clarity I would make handling of `Origin` and `Sec-Fetch-Site` the same and retrieved as follow.
```
String origin = httpRequest.getHeader(HttpHeaders.ORIGIN);
String fetchSite = httpRequest.getHeader(HttpHeaders.SEC_FETCH_SITE);
-------
if (Strings.isEmptyOrNull(fetchSite)) {
    [...]
}
----
if (Strings.isEmptyOrNull(origin)) {
   [....]
}
else {
    [....]
}

2023-03-23 14:02 UTC, Coduz commented on commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
> +        if (StringUtils.isEmpty(fetchSite) || //browser not compatible with sec fetch site (for example, safari), proceed with origin check anyway
This can be optimized with:
```
if (!"same-site".equals(fetchSite)) {
}

2023-03-23 14:02 UTC, Coduz commented on commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
> +                logger.info("<origin> not provided, is the browser incompatible with this header?");
Same as https://github.com/eclipse/kapua/pull/3750/files#diff-269c1edbd521d47e568d993fc5c2774094c3a785d8bec09e3c4dbefa1387dd81R109

Better log would be:
```
logger.info/warn("'Origin' header not present in request: {} {}. User-Agent is: {}", httpRequest.getMethod(), httpRequest.getPathInfo(), httpRequest.getUserAgent());
```
How often this header could be missing?

2023-03-23 14:02 UTC, Coduz commented on commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
> +            logger.info("HTTP same-site origin detected and allowed");
Please move this to DEBUG (since we are not much interested in allowed ones, unless we are debugging issues).
Also, similar to other logging, please add information about request path and verb.

2023-03-23 14:02 UTC, Coduz commented on commons-rest/filters/src/main/java/org/eclipse/kapua/commons/rest/filters/CORSResponseFilter.java
> +                    //this log, for browsers not supporting set fetch site, logs false positive for same origin CORS. This thing is inevitable considering that here we cannot understand if the reques
This comment I think is a bit misleading. 
This problem can occur when requests are performed by an application or via curl

2023-03-23 15:49 UTC, Agnul97 reviewed
implemented changes

2023-03-24 11:04 UTC, Coduz approved these changes

2023-03-24 11:06 UTC, merged